[package]
name = "kaede_symbol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
slab = "0.4.9"

kaede_span = { path = "../span" }
