[package]
name = "kaede_ir_type"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm17-0"] }

kaede_symbol = { path = "../symbol" }
