name: CI (macOS)

on: [push]

jobs:
  check-and-test:
    name: Check and test (Nix)
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Cache rust
        id: cache-rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            ./target/
          key: ${{ runner.os }}-nix-cargo-${{ hashFiles('**/Cargo.lock', 'flake.lock') }}

      - name: Install kaede
        run: nix develop --command bash -c "chmod +x install.py && ./install.py --no-setenv"

      - name: Run format
        run: nix develop --command cargo fmt --all -- --check

      - name: Run clippy
        run: nix develop --command cargo clippy -- -D warnings

      - name: Run test except valgrind-only cases
        run: nix develop --command cargo test --release --no-fail-fast -- --skip leak_check_with_valgrind --skip leak_check_with_no_gc_should_fail
