name: test

on: [push]

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache llvm
        uses: actions/cache@v3
        with:
          path: |
            ./llvm
          key: llvm-15.0

      - name: Install llvm
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run test
        run: cargo test --release --all-features
