name: test

on: [push]

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Restore cached llvm
        id: cache-llvm-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            ./llvm/
          key: ${{ runner.os }}-llvm-17.0

      - name: Restore cached rust
        id: cache-rust-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/
            ./target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Update apt
        run: sudo apt update

      - name: Install cmake
        run: sudo apt install -y cmake

      - name: Install valgrind
        run: sudo apt install -y valgrind

      - name: Install llvm
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17.0"
          cached: ${{ steps.cache-llvm-restore.outputs.cache-hit }}

      - name: Save llvm
        id: cache-llvm-save
        if: steps.cache-llvm-restore.outputs.cache-hit == 'false'
        uses: actions/cache/save@v3
        with:
          path: |
            ./llvm/
          key: ${{ steps.cache-llvm-restore.outputs.cache-primary-key }}

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        if: steps.cache-rust-restore.outputs.cache-hit == 'false'
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Save rust
        id: cache-rust-save
        if: steps.cache-rust-restore.outputs.cache-hit == 'false'
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/
            ./target/
          key: ${{ steps.cache-rust-restore.outputs.cache-primary-key }}

      - name: Install kaede
        run: chmod +x install.py && ./install.py

      - name: Run format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run test
        # Execute in single thread because errors occur in parallel
        run: cargo test --release --no-fail-fast -- --test-threads=1
